// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo"
	mock "github.com/stretchr/testify/mock"
)

// CommentsHandler is an autogenerated mock type for the CommentsHandler type
type CommentsHandler struct {
	mock.Mock
}

// DeleteComments provides a mock function with given fields:
func (_m *CommentsHandler) DeleteComments() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetAllComments provides a mock function with given fields:
func (_m *CommentsHandler) GetAllComments() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetMyComments provides a mock function with given fields:
func (_m *CommentsHandler) GetMyComments() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// InsertComments provides a mock function with given fields:
func (_m *CommentsHandler) InsertComments() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewCommentsHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommentsHandler creates a new instance of CommentsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommentsHandler(t mockConstructorTestingTNewCommentsHandler) *CommentsHandler {
	mock := &CommentsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
